# ---------------------------------------------------------------------------------------------------------------------
# Generate Ansible Inventory from Terraform outputs
# ---------------------------------------------------------------------------------------------------------------------

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"

  content = templatefile("${path.module}/templates/inventory.ini.tftpl", {
    login_ip        = aws_instance.login[0].public_ip
    controller_ips  = aws_network_interface.controller[*].private_ip
    compute_ips     = aws_network_interface.compute[*].private_ip
    gpu_compute_ips = aws_network_interface.gpu_compute[*].private_ip
    nfs_ips         = aws_network_interface.nfs[*].private_ip
    filesystem_ips  = aws_network_interface.filesystem[*].private_ip
  })
}

resource "local_file" "ansible_group_vars_slurm" {
  filename        = "${path.module}/../ansible/group_vars/slurm.yml"
  file_permission = "0600"

  content = <<-EOF
    ---
    # Auto-generated by Terraform
    slurm_db_host: ${split(":", module.database.endpoint)[0]}
    slurm_db_name: ${module.database.db_name}
    slurm_db_user: ${var.db_admin_username}
    slurm_db_password: ${var.db_admin_password}
  EOF
}
