---
- name: Initialise storage
  include_tasks:
    file: storage.yml

- name: Install controller
  include_tasks:
    file: install_controller.yml
  when:
  - component == 'controller'

- name: Install controller backup
  include_tasks:
    file: install_controller_backup.yml
  when:
  - component == 'controller-backup'

- name: Install compute
  include_tasks:
    file: install_compute.yml
  when:
  - component == 'compute'

- name: Install login
  include_tasks:
    file: install_login.yml
  when:
  - component == 'login'
