---
- name: Install SLURM controller
  hosts: controller
  gather_facts: false
  vars:
    component: controller
  tasks:
  - include_role:
      name: slurm

- name: Install SLURM controller backup
  hosts: controller-backup
  gather_facts: false
  vars:
    component: controller-backup
  tasks:
  - include_role:
      name: slurm

- name: Install SLURM compute
  hosts:
  - compute
  - gpu_compute
  gather_facts: false
  vars:
    component: compute
  tasks:
  - include_role:
      name: slurm

- name: Install SLURM login
  hosts: login
  gather_facts: false
  vars:
    component: login
  tasks:
  - include_role:
      name: slurm
