---
# - name: Install SLURM controller
#   hosts: controller
#   gather_facts: false
#   vars:
#     component: controller
#   tasks:
#   - include_role:
#       name: slurm

# - name: Install SLURM compute
#   hosts: compute
#   gather_facts: false
#   vars:
#     component: compute
#   tasks:
#   - include_role:
#       name: slurm

- name: Install SLURM login
  hosts: login
  gather_facts: false
  vars:
    component: login
  tasks:
  - include_role:
      name: slurm